package utils

const (
	E_not_found                   = "not_found"
	E_user_existed                = "user_existed"
	E_user_not_existed            = "user_not_existed"
	E_not_found_user_id           = "not_found_user_id"
	E_internal_error              = "internal errors"
	E_not_found_id                = "not_found_id"
	E_invalid_state               = "invalid_state"
	E_can_not_insert              = "can_not_insert"
	E_can_not_update              = "can_not_update"
	E_can_not_delete              = "can_not_delete"
	E_not_found_role_id           = "not_found_role_id"
	E_invalid_token               = "invalid_token"
	E_invalid_sigature            = "invalid_signature"
	E_not_found_username          = "not_found_username"
	E_username_is_incorrect       = "username_is_incorrect"
	E_password_is_incorrect       = "password_is_incorrect"
	E_not_found_password          = "not_found_password"
	E_category_name_empty         = "category_name_empty"
	E_product_banner_word         = "product_banner_word"
	E_invalid_name                = "invalid_name"
	E_invalid_email               = "invalid_email"
	E_invalid_phone_number        = "invalid_phone_number"
	E_invalid_category_id         = "invalid_category_id"
	E_can_not_update_product      = "can_not_update_product"
	E_can_not_update_product_type = "can_not_update_product_type"
	E_not_found_product           = "not_found_product"
	E_can_not_delete_product_type = "can_not_delete_product_type"
	E_can_not_delete_product      = "can_not_delete_product"
	E_not_found_product_type      = "not_found_product_type"
	E_can_not_insert_product      = "can_not_insert_product"
	E_not_found_category_id       = "not_found_category_id"
	E_category_logo_empty         = "category_logo_empty"
	E_invalid_store_id            = "invalid_store_id"
	E_invalid_price               = "invalid_price"
	E_not_found_category          = "not_found_category"
)
